services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    hostname: devcontainer
    ports:
      - "${WEBAPP_PORT:-18000}:3000"
      - "${WEBAPP_EMAIL_PORT:-18005}:3001"
      - "${WEBAPP_NOVU_PORT:-18006}:3002"
    env_file: [".env"]
    volumes:
      - ./:/workspaces/spotteur:cached
      - "webapp-worker_storage:${TEMPORAL_DEFAULT_STORAGE_DIR:-/storage}"
    command: "sleep infinity"
  inbucket:
    image: "inbucket/inbucket:sha-6eff554"
    environment:
      INBUCKET_MAILBOXNAMING: "full"
      INBUCKET_SMTP_ADDR: "0.0.0.0:25"
      INBUCKET_POP3_ADDR: "0.0.0.0:110"
      INBUCKET_LOGLEVEL: "warn"
    volumes:
      - "inbucket_config:/config"
      - "inbucket_storage:/storage"
    ports:
      - "${INBUCKET_PORT:-18004}:9000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:9000/status || exit 1"]
    restart: "unless-stopped"

  webapp:
    profiles: ["disable-on-dev"]
  webapp-worker:
    profiles: ["disable-on-dev"]
  volume-permission-helper:
    profiles: ["disable-on-dev"]

volumes:
  inbucket_config:
  inbucket_storage:
